services:

  mariadb:
      #image: mariadb
      build:
        context: ./mariadb
        dockerfile: Dockerfile
      restart: always
      networks:
       - front
      volumes:
       - db-data:/var/lib/mysql
      env_file:
      - .env

  wordpress:
      # image: wordpress:5-fpm-alpine
      build:
        context: ./wordpress
        dockerfile: Dockerfile
      restart: always
      networks:
       - front
       - back
      #environment:
      # - WORDPRESS_DB_HOST=mariadb
      # - WORDPRESS_DB_NAME=example
      # - WORDPRESS_DB_USER=example
      # - WORDPRESS_DB_PASSWORD=example
      ports:
       - 9000:9000
      volumes:
       - wordpress-data:/var/www/html
      # - ./wordpress/wp-config-docker:/var/www/html/wp-config.php
      #  - /data/html:/var/www/html
      depends_on:
       - mariadb
      env_file:
       - .env

  nginx:
      # image: nginx
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: my-nginx
      ports:
        - "443:443"
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - wordpress-data:/var/www/html
      # links:
      #   - wordpress
      depends_on:
        - wordpress
      networks:
        - back
volumes:
  db-data:
  wordpress-data:
  
networks:
  front:
  back:
