FROM nginx
# # Use Alpine as the base image
# FROM alpine:3.14

# # Update the package repository and install Nginx
# RUN apk update && apk add nginx

# # Create Nginx directories and set permissions
# RUN mkdir -p /run/nginx && \
#     mkdir -p /var/www/html && \
#     chown -R nginx:nginx /var/lib/nginx && \
#     chown -R nginx:nginx /var/www/html

# # Optionally, copy your custom Nginx configuration files if you have them
# # COPY nginx.conf /etc/nginx/nginx.conf

# # Expose port 80 (HTTP)
# EXPOSE 80

# # Define the entry point for the container
# CMD ["nginx", "-g", "daemon off;"]
